#/bin/bash

set -ex

touch PyActionFamilyNode.py
touch PyActionNode.py
touch PyArchiveEntry.py
touch PyAttribute.py
touch PyAudioTrack.py
touch PyBatch.py
touch PyBatchIteration.py
touch PyBrowser.py
touch PyClip.py
touch PyClipNode.py
touch PyCoCameraAnalysis.py
touch PyCoCompass.py
touch PyCoNode.py
touch PyCompassNode.py
touch PyDesktop.py
touch PyExporter.py
touch PyFlameObject.py
touch PyFolder.py
touch PyGMaskTracerNode.py
touch PyHDRNode.py
touch PyHDRTimelineFX.py
touch PyImageNode.py
touch PyLibrary.py
touch PyMarker.py
touch PyMediaHub.py
touch PyMediaHubFilesEntry.py
touch PyMediaHubFilesFolder.py
touch PyMediaHubFilesTab.py
touch PyMediaHubFilesTabOptions.py
touch PyMediaHubProjectsEntry.py
touch PyMediaHubProjectsFolder.py
touch PyMediaHubTab.py
touch PyMediaPanel.py
touch PyMessages.py
touch PyNode.py
touch PyOFXNode.py
touch PyPaintNode.py
touch PyProject.py
touch PyProjectSelector.py
touch PyReel.py
touch PyReelGroup.py
touch PyRenderNode.py
touch PyResolution.py
touch PySearch.py
touch PySegment.py
touch PySequence.py
touch PySequenceGroup.py
touch PySubtitleTrack.py
touch PyTime.py
touch PyTimeline.py
touch PyTimelineFX.py
touch PyTrack.py
touch PyTransition.py
touch PyUser.py
touch PyUsers.py
touch PyVersion.py
touch PyWorkspace.py
touch PyWriteFileNode.py
touch __loader__.py